language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 3.1

script:
  - dotnet restore
  - dotnet build
  - dotnet test BlockingCollectionsExtensions.Unit.Tests/BlockingCollectionsExtensions.Unit.Tests.csproj

global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1