name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build-test-pack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x

      - name: Restore
        run: dotnet restore BlockingCollectionExtensions.sln

      - name: Build net8.0
        run: dotnet build BlockingCollectionExtensions/BlockingCollectionExtensions.csproj --configuration Release --framework net8.0 --no-restore

      - name: Build netstandard2.1
        run: dotnet build BlockingCollectionExtensions/BlockingCollectionExtensions.csproj --configuration Release --framework netstandard2.1 --no-restore

      - name: Test
        run: dotnet test BlockingCollectionsExtensions.Unit.Tests/BlockingCollectionsExtensions.Unit.Tests.csproj --configuration Release --no-build --framework net8.0

      - name: Pack
        run: dotnet pack BlockingCollectionExtensions/BlockingCollectionExtensions.csproj --configuration Release --no-build -p:EnablePackageValidation=true -o artifacts
